[CHECK codingstyle

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -13,34 +13,34 @@ env:
   BANNED_FUNCTIONS: "strcpy strcat gets system"
 
 jobs:
-check_coding_style:
-  name: "Coding Style Check"
-  runs-on: ubuntu-latest
-  continue-on-error: false
-  container:
-    image: ghcr.io/epitech/coding-style-checker:latest
-  if: ${{ github.repository != 'EpitechPGEPromo2029/B-DOP-200-MLN-2-1-chocolatine-sacha.lamour' }}
-  steps:
-    - uses: actions/checkout@v4
-    - id: check_coding_style
-      run: |
-        bash -c '
-        check.sh $(pwd) $(pwd)
-        # Vérifie si le fichier de log existe et n'est pas vide
-        if [[ -s coding-style-reports.log ]]; then
-          echo "Coding style errors detected:"
-          # Lit le fichier ligne par ligne
-          while IFS=':' read -r file line severity code; do
-            # Nettoie les chemins (supprime ./ au début)
-            file=${file#./}
-            # Formate et affiche l'erreur avec les annotations GitHub
-            echo "::error file=${file},line=${line},title=${severity} ${code}::Coding style violation detected"
-          done < coding-style-reports.log
-          exit 1
-        else
-          echo "No coding style errors detected ✅"
-          exit 0
-        fi '
+  check_coding_style:
+    name: "Coding Style Check"
+    runs-on: ubuntu-latest
+    continue-on-error: false
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    if: ${{ github.repository != 'EpitechPGEPromo2029/B-DOP-200-MLN-2-1-chocolatine-sacha.lamour' }}
+    steps:
+      - uses: actions/checkout@v4
+      - id: check_coding_style
+        run: |
+          bash -c '
+          check.sh $(pwd) $(pwd)
+          # Vérifie si le fichier de log existe et n'est pas vide
+          if [[ -s coding-style-reports.log ]]; then
+            echo "Coding style errors detected:"
+            # Lit le fichier ligne par ligne
+            while IFS=':' read -r file line severity code; do
+              # Nettoie les chemins (supprime ./ au début)
+              file=${file#./}
+              # Formate et affiche l'erreur avec les annotations GitHub
+              echo "::error file=${file},line=${line},title=${severity} ${code}::Coding style violation detected"
+            done < coding-style-reports.log
+            exit 1
+          else
+            echo "No coding style errors detected ✅"
+            exit 0
+          fi '
 
   check_banned_functions:
     name: "Check Banned Functions"
