TEST

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,86 +1,97 @@
-name: Chocolatine CI
-
+name: chocolatine
+run-name: ${{github.actor}} choco's check
 on:
   push:
     branches-ignore:
-      - ga-ignore-*
+      - " ga-ignore-"
   pull_request:
     branches-ignore:
-      - ga-ignore-*
-
+      - " ga-ignore-"
 env:
   MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-MLN-2-1-chocolatine-sacha.lamour.git"
   EXECUTABLES: "my_radar"
-
 jobs:
   check_coding_style:
-    name: Check Coding Style
     runs-on: ubuntu-latest
-    continue-on-error: false
-    container:
-      image: ghcr.io/epitech/coding-style-checker:latest
+    container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
 
-      - name: Run Coding Style Check
+      - name: Checkout GH repository
+        uses: actions/checkout@master
+        with:
+          repository: ''
+
+      - name: Run coding-style
         run: check.sh $(pwd) $(pwd)
 
-      - name: Display Errors
-        if: failure()
-        run: cat coding-style-reports.log && exit 1
+      - name: Create annotation for coding-style errors
+        run: |
+          input=/tmp/coding-style-reports.log
+          while IFS= read -r -a line; do
+            fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
+            echo "::error title=${fields[2]} coding style error,file=${fields[0]},line=${fields[1]}::${fields[3]}"
+          done < $input
+
+      - name: Report banana result
+        run: |
+          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+            exit 1
+          fi
 
   check_program_compilation:
-    name: Check Compilation
     runs-on: ubuntu-latest
-    continue-on-error: false
-    container:
-      image: epitechcontent/epitest-docker
+    timeout-minutes: 2
+    container: epitechcontent/epitest-docker:latest
     needs: check_coding_style
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
 
-      - name: Compile Project
-        run: timeout 120 make
+      - name: Checkout GH repository
+        uses: actions/checkout@master
+        with:
+          repository: ''
 
-      - name: Clean Project
+      - name: Compile repository
+        run: make
+
+      - name: Clean repository
         run: make clean
 
-      - name: Verify Executables
+      - name: Check file
         run: |
-          for exe in $(echo "$EXECUTABLES" | tr ',' ' '); do
-            if [ ! -x "$exe" ]; then
-              echo "Executable $exe not found or not executable" && exit 1
+          for file in ${{ env.EXECUTABLES }};do
+             if [ ! -x "$file" ]; then
+              echo "File $file does not exist or is not executable"
+              exit 1
             fi
           done
 
   run_tests:
-    name: Run Tests
     runs-on: ubuntu-latest
-    continue-on-error: false
-    container:
-      image: epitechcontent/epitest-docker
-    needs: check_program_compilation
+    timeout-minutes: 2
+    container: epitechcontent/epitest-docker:latest
+    needs:  check_program_compilation
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
 
-      - name: Run Tests
-        run: timeout 120 make tests_run
+      - name: Checkout GH repository
+        uses: actions/checkout@master
+        with:
+          repository: ''
+
+      - name: Compile tests binaries
+        run: make tests_run
 
   push_to_mirror:
-    name: Push to Mirror
     runs-on: ubuntu-latest
-    needs: run_tests
-    continue-on-error: false
+    needs:  run_tests
     if: github.event_name == 'push'
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Mirror Repository
-        uses: pixta-dev/repository-mirroring-action@v1
+      - uses: actions/checkout@v3
         with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.SSH_SECRET_KEY }}
+          fetch-depth: 0
+      - uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.SSH_PRIVATE_KEY }}
