TEST

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -22,18 +22,20 @@ jobs:
       - uses: actions/checkout@v4
       - id: check_coding_style
         run: |
-          check.sh $(pwd) $(pwd)
-          CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
-          while IFS= read -r ERRORS; do
-            array=(`echo $ERRORS | sed 's/:/\n/g'`)
-            echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
-          done < $(pwd)/coding-style-reports.log
-          if [[ -s $(pwd)/coding-style-reports.log ]]
-          then
-            exit 1
-          else
-            echo No coding style errors detected
-          fi
+          bash -c '
+            check.sh $(pwd) $(pwd)
+            CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
+            while IFS= read -r ERRORS; do
+              array=(`echo $ERRORS | sed "s/:/\\n/g"`)
+              echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
+            done < $(pwd)/coding-style-reports.log
+            if [[ -s $(pwd)/coding-style-reports.log ]]; then
+              exit 1
+            else
+              echo No coding style errors detected
+            fi
+          '
+
 
   check_program_compilation:
     name: Check Compilation
