[BACK]

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -16,6 +16,7 @@ jobs:
   check_coding_style:
     name: "Coding Style Check"
     runs-on: ubuntu-latest
+    continue-on-error: false
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
     if: ${{ github.repository != 'EpitechPGEPromo2029/B-DOP-200-MLN-2-1-chocolatine-sacha.lamour' }}
@@ -87,6 +88,37 @@ jobs:
             fi
           done
 
+  check_memory_leaks:
+    name: "Memory Leak Check"
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker
+    needs: check_program_compilation
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Run Valgrind on Executables
+        run: |
+          make
+          found=0
+          for file in ${{ vars.EXECUTABLES }}; do
+            if [ ! -x "$file" ]; then
+              echo "::error:: Executable '$file' not found or not executable!"
+              found=1
+              continue
+            fi
+            echo "Running Valgrind on $file..."
+            valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 "./$file"
+            if [[ $? -ne 0 ]]; then
+              echo "::error:: Memory leaks detected in $file!"
+              found=1
+            fi
+          done
+          if [[ $found -eq 1 ]]; then
+            exit 1
+          fi
+
   run_tests:
     name: Run Tests
     runs-on: ubuntu-latest
@@ -125,8 +157,7 @@ jobs:
   notify_discord:
     name: "Notify Discord"
     runs-on: ubuntu-latest
-    needs: [check_coding_style, check_banned_functions, check_program_compilation, run_tests]
-    if: always()
+    needs: [check_coding_style, check_banned_functions, check_program_compilation, check_memory_leaks, run_tests]
     steps:
       - name: Send Notification to Discord
         env:
